#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/Users/yinawei/opt/miniconda3/envs/bmtk-ateam2/lib/python2.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/Users/yinawei/opt/miniconda3/envs/bmtk-ateam2/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/Users/yinawei/Dropbox/WEI_MS_MOUSE_2020/Code/Mouse-all-active-models-EAP/Examples/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
